feat: add otkafka processor
DoNewsCode/core pull request #134
Opened 2021-05-14 05:48 UTC by GGXXLL

### What is it?
It is an abstraction of Kafka consumer process. 

Users only need to care about how to parse message and process data (implements `processor.Handler`). 

They don't need to care about how to consume message and transfer data.

### How to use it?
```golang
package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/DoNewsCode/core"
	"github.com/DoNewsCode/core/di"
	"github.com/DoNewsCode/core/otgorm"
	"github.com/DoNewsCode/core/otkafka"
	"github.com/DoNewsCode/core/otkafka/processor"
	"github.com/segmentio/kafka-go"
	"gorm.io/gorm"
)

type event struct {
	Id   int
	Name string
}

type handler struct {
	db *gorm.DB
}

func newHandler(db *gorm.DB) processor.Out {
	return processor.NewOut(&handler{db: db})
}

func (h *handler) Info() *processor.Info {
	// Set the name of the consumer reader to default. Same name as in configuration.
	return &processor.Info{
		Name:      "default",
		BatchSize: 3,
	}
}

func (h *handler) Handle(ctx context.Context, msg *kafka.Message) (interface{}, error) {
	// Decode message
	e := &event{}
	if err := json.Unmarshal(msg.Value, &e); err != nil {
		return nil, err
	}

	// Dirty data
	if e.Id < 0 {
		return nil, nil
	}

	return e, nil
}

func (h *handler) Batch(ctx context.Context, data []interface{}) error {
	// Convert the interface to the correct data type
	save := make([]*event, len(data))
	for i, e := range data {
		save[i] = e.(*event)
	}

	// Do some thing
	if err := h.db.WithContext(ctx).Table("example").Save(save).Error; err != nil {
		return err
	}

	return nil
}

func main() {
	// Load config
	c := core.New(
		core.WithInline("kafka.reader.default.brokers", "127.0.0.1:9092"),
		core.WithInline("kafka.reader.default.topic", "example"),
		core.WithInline("kafka.reader.default.groupID", "default"),
		core.WithInline("kafka.reader.default.startOffset", -1),

		core.WithInline("gorm.default.database", "mysql"),
		core.WithInline("gorm.default.dsn", "root@tcp(127.0.0.1:3306)/app?charset=utf8mb4&parseTime=True&loc=Local"),

		core.WithInline("http.disable", "true"),
		core.WithInline("grpc.disable", "true"),
		core.WithInline("cron.disable", "true"),
		core.WithInline("log.level", "debug"),
	)
	// Provide dependence
	c.ProvideEssentials()
	c.Provide(otkafka.Providers())
	c.Provide(otgorm.Providers())

	// Provide your handlers
	c.Provide(di.Deps{
		newHandler,
	})

	c.AddModuleFunc(processor.New)

	// Run serve
	if err := c.Serve(context.Background()); err != nil {
		panic(err)
	}
}
```

2021-05-17 05:50 UTC, Reasno requested changes

2021-05-17 05:50 UTC, Reasno commented on otkafka/processor/processor.go
> +				if h.info.autoCommit() {
这个区分真的有必要吗

2021-05-17 05:50 UTC, Reasno commented on otkafka/processor/processor.go
> +		data = data[0:0]
这块的含义是什么？

2021-05-17 05:50 UTC, Reasno commented on otkafka/processor/processor.go
> +			return err
发生错误时data和message没有清空，是故意的吗

2021-05-17 05:50 UTC, Reasno commented on otkafka/processor/processor.go
> +		data = data[0:0]
推荐，doFunc从参数中接收 data和msg，而不是直接闭包使用。避免了很多可能出现的问题。

2021-05-17 05:50 UTC, Reasno commented on otkafka/processor/processor.go
> +					return err
这个错误的测试用例很有必要。目前从代码分析应该是有问题的。

2021-05-17 05:50 UTC, Reasno commented on otkafka/processor/info.go
> +type Info struct {
这个用私有成员变量，公开方法更好吧

2021-05-17 06:21 UTC, GGXXLL commented on otkafka/processor/processor.go
> +			return err
抛出去error了, 服务应该会退出, 就没管了

2021-05-17 06:22 UTC, GGXXLL commented on otkafka/processor/processor.go
> +		data = data[0:0]
处理成功之后, 清空切片. 闭包已经改了.

2021-05-17 06:22 UTC, GGXXLL commented on otkafka/processor/processor.go
> +					return err
嗯, 补充了

2021-05-17 06:22 UTC, GGXXLL commented on otkafka/processor/info.go
> +type Info struct {
好的

2021-05-19 03:20 UTC, Reasno approved these changes

2021-05-19 10:36 UTC, merged